### ISSUE TITLE
Redmine 2.6

### ISSUE THREAD

**Issue by pyroit** [jbbarth/redmine_sudo#3]
Hi,
i have tried to install the plugin unter 2.6 but I can not get i working.

The migration does not work: 

(See full trace by running task with --trace)
bash-3.2$ ruby bin/rake redmine:plugins RAILS_ENV=production --trace
** Invoke redmine:plugins (first_time)
** Execute redmine:plugins
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:118:in `find'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:246:in `requires_redmine_plugin'
/Applications/redmine3/apps/redmine/htdocs/plugins/redmine_sudo/init.rb:19:in `block in <top (required)>'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `instance_eval'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `register'
/Applications/redmine3/apps/redmine/htdocs/plugins/redmine_sudo/init.rb:10:in `<top (required)>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in `block in load'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `each'
/Applications/redmine3/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `load'
/Applications/redmine3/apps/redmine/htdocs/config/initializers/30-redmine.rb:19:in `<top (required)>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Applications/redmine3/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/application.rb:103:in `require_environment!'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Applications/redmine3/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Applications/redmine3/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
bin/rake:16:in `load'
bin/rake:16:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

But also after I did the integration manually redmine does not start: i got the  "We're sorry, but something went wrong." massage.

Your plugin looks really good, i pretty much like the idea not being admin all the time.

Thank you very much in advance 

Moritz

**Comment by jbbarth** [comment]
Sorry the error is unclear (redmine's fault) and the Readme is not up to date (my fault) : you need to also install the "redmine_base_deface" plugin (by me) to make redmine_sudo work. Please install both plugins in the plugins/ directory without changing their name and follow the instructions on both Readme files.

Again sorry for the wrong doc I'll update it soon!

**Comment by pyroit** [comment]
Thank you very much

**Comment by tofi86** [comment]
I can confirm that the plugin works well in redmine 2.6.1 when having `redmine_base_deface` installed!
