### ISSUE TITLE
coping with other themes

### ISSUE THREAD

**Issue by DarkSideGeek** [jbbarth/redmine_sudo#9]
Pretty cool feature. Good for that extra dose of safety. Also works well with https://github.com/leonko/redmine_pretend, which allows you to masquerade as another user. So you can be Normal, elevate yourself to Admin [sudo], impersonate someone to see what they would see [su - user], and then drop back down to your mortal self [sudo -k], all without logging in & out.

Works great on the Default theme. On Pepper, which is more of a multi-line top header, it all gets squished down:

![mortaluser](https://cloud.githubusercontent.com/assets/1418537/12314475/48586f1e-ba26-11e5-8cc7-93b8e323e87a.png)
![adminuser](https://cloud.githubusercontent.com/assets/1418537/12314476/48707622-ba26-11e5-8239-e1175c8d3e39.png)

**Comment by DarkSideGeek** [comment]
A little bit more about the above images. I had thought that aesthetically I was just faced with the theme problem of 3 lines squeezed into the spacing of 2. But it goes a bit deeper than that. It seems that the "active area" of the SUDO button is very large. I can click on the "Logged in as..." link above SUDO to access the user profile. But I cannot click on "My Account" or "Sign Out" below SUDO because it's clickable area has encroached upon that real estate.

Even if no special fixes are made to adapt to the multi-line Pepper theme, is there anything that can be done to shrink the mouseover area of the SUDO button? I would like to be able to reach the logout...

**Comment by nanego** [comment]
I'm closing this issue, as the latest version of the plugin now pushes the link to the account_menu, making it more compatible with other themes.
